name: Sync and Rewrite Repository Every 10 Days

on:
  schedule:
    - cron: "0 0 */10 * *" # Runs every 10 days at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone the source repository
      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.SOURCE_REPO }}
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      # Step 2: Rewrite All Commits
      - name: Rewrite All Commits
        run: |
          git filter-branch --env-filter '
          CORRECT_NAME="${{ secrets.CORRECT_NAME }}"
          CORRECT_EMAIL="${{ secrets.CORRECT_EMAIL }}"

          if [ "$GIT_COMMITTER_EMAIL" != "$CORRECT_EMAIL" ]; then
              export GIT_COMMITTER_NAME="$CORRECT_NAME"
              export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
          fi
          if [ "$GIT_AUTHOR_EMAIL" != "$CORRECT_EMAIL" ]; then
              export GIT_AUTHOR_NAME="$CORRECT_NAME"
              export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
          fi
          ' --tag-name-filter cat -- --all
          rm -rf .git/refs/original/
          git reflog expire --expire=now --all
          git gc --prune=now --aggressive

      # Step 3: Push to the target repository
      - name: Push to Target Repository
        run: |
          git remote set-url origin ${{ secrets.TARGET_REPO_URL }}
          git push --force --tags https://${{ secrets.PAT }}@${{ secrets.TARGET_REPO_URL }} "refs/heads/*"
